config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/policy',     to: 'static_pages#policy'
  get '/upload',     to: 'static_pages#upload'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/posts/likes/:post_id/create', to: 'likes#create'
  post '/posts/likes/:post_id/destroy', to: 'likes#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:show, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_circle.html.erb
<div class="">
  <%= link_to(notifications_path) do %>
    <% if unchecked_notifications.any? %>
      <span class="fa-stack">
        <i class="far fa-bell"></i>
      </span>
    <% else %>
      <i class="fas fa-bell"></i>
    <% end %>
  <% end %>
</div>

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<div class="col-md-8 mx-auto">
  <div class="form-inline" %>
    <table class="table">
      <tbody>
        <tr>
          <td><span>
            <%= link_to user_path(visitor) do %>
              <strong>
                <%= visitor.name %>
              </strong>
              <%= 'さんが' %>
            <% end %>
          </span>
            <% case notification.action %>
            <% when 'follow' %>
              <%= "あなたをフォローしました" %>
            <% when 'like' %>
              <%= link_to 'あなたの投稿', notification.post, style: "font-weight: bold;" %>
              <%= "にいいねしました" %>
            <% when 'comment' %>
              <% if notification.post.user_id == visited.id %>
                <%= link_to "あなたの投稿", notification.post, style: "font-weight: bold;" %>
              <% else %>
                <span>
                  <%= link_to post_path(notification.post) do %>
                    <%= image_tag avatar_url(notification.post.user).to_s, class: "icon_mini" %>
                    <strong>
                      <%= notification.post.user.name + 'さんの投稿' %>
                    </strong>
                  <% end %>
                </span>
              <% end %>
              <%= "にコメントしました" %>
            <% end %>
          <p class="text-muted mb-0">
            <%= Comment.find_by(id: notification.comment_id)&.content %>
          </p>
          <div class="small text-muted text-right">
            <%= time_ago_in_words(notification.created_at).upcase %>
          </div></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/notifications/index.html.erb
<div class="container mx-auto">
  <% notifications = @notifications.where.not(visitor_id: current_user.id) %>
  <% if notifications.exists? %>
    <%= render notifications %>
    <%= paginate notifications %>
  <% else %>
    <p class="center">通知はありません</p>
  <% end %>
</div>