config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/policy',     to: 'static_pages#policy'
  get '/upload',     to: 'static_pages#upload'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/posts/likes/:post_id/create', to: 'likes#create'
  post '/posts/likes/:post_id/destroy', to: 'likes#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:show, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  attr_accessor :remember_token
  mount_uploader :profile_image, PictureUploader
  validates :name, unless: :uid?, presence: true, length: { maximum: 30 }
  validates :nickname, unless: :uid?, presence: true, length: { maximum: 30 }, uniqueness: { scope: :name }
  has_secure_password validations: false
  validates :password, unless: :uid?, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def feed
    Post.where("user_id IN (?) OR user_id = ?", following_ids, id)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end

  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    name = auth[:info][:name]
    nickname = auth[:info][:name]

    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
      user.nickname = nickname
    end
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.page(params[:page]).search(params[:search])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Insta Clone App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page])
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:name, :nickname, :password, :password_confirmation, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_logout_and_setting.html.erb
<div class="logout-and-setting">
  <% if current_user?(@user) %>
    <p>
      <%= link_to edit_user_path(current_user), class: 'edit-logout-bottun' do %>
        <i class="fas fa-user-edit"></i> プロフィールを編集
      <% end %>
    </p>
    <p>
      <%= link_to logout_path, class: 'edit-logout-bottun', method: :delete do %>
        <i class="fas fa-sign-out-alt"></i> ログアウトする
      <% end %>
    </p>
  <% else %>
    <%= render 'follow_form' if logged_in? %>
  <% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォローを解除", class: "btn btn-secondary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<div class="container">
  <h1 class="center">プロフィール編集</h1>

  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :nickname, 'ニックネーム' %>
        <%= f.text_field :nickname, class: 'form-control' %>

        <%=f.label :profile_image, 'プロフィール画像' %>
        <%= f.file_field :profile_image %>

        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "パスワード確認" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "プロフィールを更新する", class: "btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <%= form_tag(users_path, :method => 'get') do %>
        <div class="input-group mb-3">
          <%= text_field_tag :search, params[:search], :class => "form-control", :placeholder => "ユーザーを検索...", "aria-label" => "...", "aria-describedby" => "button-addon2" %>
          <div class="input-group-append">
            <%= button_tag "検索", :name => nil, :id => "button-addon2", :class => "btn btn-outline-secondary" %>
          </div>
        </div>
      <% end %>
      <table class="table">
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td>
                <% if user.profile_image?%>
                  <%= image_tag user.profile_image.url, class: 'index_profile_image' %>
                <% else %>
                  <%= image_tag 'default_user_image.jpeg', class: 'index_profile_image' %>
                <% end %>
                <%= link_to user.name, user, class: 'index_profile_name' %>
              </td>
              <td>
                <%= user.nickname %>
                <% if current_user.admin? && !current_user?(user) %>
                  <%= link_to "delete", user, method: :delete, data: { confirm: "ユーザーを削除します。よろしいですか？" } %>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <% provide(:title, 'Sign up') %>
  <h1 class="center">Sign up</h1>

  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :nickname, 'ニックネーム' %>
        <%= f.text_field :nickname, class: 'form-control' %>

        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "パスワード確認" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "アカウントを作成する", class: "btn btn-outline-secondary" %>
      <% end %>
      <%= link_to policy_path do %>
        <div class="sighup-policy">
          <i class="far fa-file-alt"></i> 利用規約
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container center">
  <div class="row">
    <div class="col-md-4">
      <% if @user.profile_image?%>
        <%= image_tag @user.profile_image.url, class: 'profile_image' %>
      <% else %>
        <%= image_tag 'default_user_image.jpeg', class: 'profile_image' %>
      <% end %>
    </div>
    <div class="col-md-8">
      <h1><%= @user.name %>    <small class="text-muted"><%= @user.nickname %></small></h1>
      <table class="table center">
        <tbody>
          <tr>
            <section class="stats">
              <% @user ||= current_user %>
              <div class="stats">
                <td>
                  <a href="<%= following_user_path(@user) %>">
                    <strong id="following" class="stat">
                      <%= @user.following.count %>人をフォロー中
                    </strong>
                  </a>
                </td>
                <td>
                  <a href="<%= followers_user_path(@user) %>">
                    <strong id="followers" class="stat">
                      フォロワー<%= @user.followers.count %>人
                    </strong>
                  </a>
                </td>
              </div>
            </section>
            <td>
              <%= render 'logout_and_setting'%>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <% if @user.posts.any? %>
    <h3>Posts (<%= @user.posts.count %>)</h3>
    <div class="row posts">
      <% @user.posts.each do |post| %>
        <div class="col-md-4">
          <li id="post-<%= post.id %>">
            <% if post.picture? %>
              <%= link_to image_tag(post.picture.url, class: 'show_picture'), post_path(post) %>
            <% end %>
          </li>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <% @users.each do |user| %>
          <li>
            <% if user.profile_image?%>
              <%= image_tag user.profile_image.url, class: 'index_profile_image' %>
            <% else %>
              <%= image_tag 'default_user_image.jpeg', class: 'index_profile_image' %>
            <% end %>
            <%= link_to user.name, user %>
            <%= user.nickname %>
          </li>
        <% end %>
      </ul>
      <%= paginate @users %>
    <% end %>
  </div>
</div>