config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/policy',     to: 'static_pages#policy'
  get '/upload',     to: 'static_pages#upload'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/posts/likes/:post_id/create', to: 'likes#create'
  post '/posts/likes/:post_id/destroy', to: 'likes#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:show, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-bottom">
      <a class="nav-link disabled" href="#">The Instagram Clone App by Asai Shinji</a>
      <% if logged_in? %>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <%= content_tag :li ,class: "nav-item justify-content-end" do%>
              <%=link_to upload_path, class:"nav-link" do%>
                <i class="far fa-plus-square"></i> Image Upload
              <%end%>
            <%end%>
          </ul>
        </div>
      <% end %>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fab fa-instagram"></i> Insta Clone App
      <% end %>
      <% if logged_in? %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <%= content_tag :li ,class: "nav-item" do%>
              <%=link_to users_path, class:"nav-link" do%>
                <i class="far fa-compass"></i> All Users
              <%end%>
            <%end%>
            <%= content_tag :li ,class: "nav-item" do%>
              <%=link_to notifications_path, class:"nav-link" do%>
                <i class="far fa-bell"></i> Nortification
              <%end%>
            <%end%>
            <%= content_tag :li ,class: "nav-item" do%>
              <%=link_to current_user, class:"nav-link" do%>
                <i class="far fa-user"></i> Profile
              <%end%>
            <%end%>
          </ul>
        </div>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>